version: '3'
services:
  mariadb:
    image: 'mariadb:10.6.12'
    container_name: 'mariadbcontainer'
    environment:
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=anna
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
  giteaapp:
    image: 'anicnkakb/giteaapp'
    ports:
      - "3000:3000" # Перенаправлення портів для додатку
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_TYPE=MySQL
      - DB_NAME=gitea
      - DB_USER=anna
      - DB_PASSWD=${DB_PASSWORD}
volumes:
  mariadb_data:
